[2018-10-12 07:54:53 PM] - [MainThread] - [output_log.py-line:43] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 07:54:53 PM] - [MainThread] - [output_log.py-line:43] [INFO] https://api.github.com/user
[2018-10-12 07:54:53 PM] - [MainThread] - [output_log.py-line:41] [DEBUG] 登陆成功
[2018-10-12 07:54:53 PM] - [MainThread] - [output_log.py-line:41] [DEBUG] 连接数据库了
[2018-10-12 07:55:15 PM] - [MainThread] - [output_log.py-line:45] [WARNING] 增加用户信息错误
[2018-10-12 07:57:48 PM] - [MainThread] - [output_log.py-line:41] [DEBUG] 退出系统，关闭数据库连接
[2018-10-12 08:09:39 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 08:09:39 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 08:09:39 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 08:10:07 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 08:10:09 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 401 83
[2018-10-12 08:10:09 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 08:10:09 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 08:10:09 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 08:10:10 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 08:10:11 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 401 83
[2018-10-12 08:10:11 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 08:10:11 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 08:10:11 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 08:10:11 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败，已锁定
[2018-10-12 08:28:59 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 08:28:59 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 08:28:59 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 08:29:01 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 08:29:03 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 401 83
[2018-10-12 08:29:03 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 08:29:03 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 08:29:03 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 08:29:05 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 08:29:07 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 401 83
[2018-10-12 08:29:07 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 08:29:07 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 08:29:07 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 08:29:07 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败，已锁定
[2018-10-12 08:29:16 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败，已锁定
[2018-10-12 08:29:25 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败，已锁定
[2018-10-12 08:35:02 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 08:35:02 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 08:35:02 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 08:35:08 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 08:35:12 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 401 83
[2018-10-12 08:35:12 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 08:35:12 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 08:35:12 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 08:35:13 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 08:35:14 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 401 83
[2018-10-12 08:35:14 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 08:35:14 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 08:35:14 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 08:35:14 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败，已锁定
[2018-10-12 08:35:22 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败，已锁定
[2018-10-12 08:37:51 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 08:37:51 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 08:37:51 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 08:37:51 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 08:37:53 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 401 83
[2018-10-12 08:37:53 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 08:37:53 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 08:37:53 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 08:37:54 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 08:37:55 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 401 83
[2018-10-12 08:37:55 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 08:37:55 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 08:37:55 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 08:37:55 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败，已锁定
[2018-10-12 08:37:58 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败，已锁定
[2018-10-12 08:38:30 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 08:38:30 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 08:38:30 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 08:38:42 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 08:38:42 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 08:38:42 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 08:38:45 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 08:38:46 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 401 83
[2018-10-12 08:38:46 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 08:38:46 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 08:38:46 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 08:38:46 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败，已锁定
[2018-10-12 08:38:49 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败，已锁定
[2018-10-12 08:39:14 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 08:39:14 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 08:39:14 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 08:39:16 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 08:39:17 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 401 83
[2018-10-12 08:39:17 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 08:39:17 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 08:39:17 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 08:39:18 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 08:39:19 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 401 83
[2018-10-12 08:39:19 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 08:39:19 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 08:39:19 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 08:39:19 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败，已锁定
[2018-10-12 08:39:22 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败，已锁定
[2018-10-12 09:15:37 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 09:15:37 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 09:15:37 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 09:15:39 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 09:15:40 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 401 83
[2018-10-12 09:15:40 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 09:15:40 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 09:15:40 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 09:15:41 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 09:15:42 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 401 83
[2018-10-12 09:15:42 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 09:15:42 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 09:15:42 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 09:15:42 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败，已锁定
[2018-10-12 09:15:44 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败，已锁定
[2018-10-12 09:18:23 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 09:18:23 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 09:18:23 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 09:18:23 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 09:23:50 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 09:24:26 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 09:24:29 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 09:24:32 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 09:24:32 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 09:24:32 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 09:24:32 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 09:24:53 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 增加用户信息
[2018-10-12 09:24:53 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] {'name': 'caonima', 'age': '25', 'tel': '0987654321', 'address': 'earth'}
[2018-10-12 09:25:10 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 增加用户信息错误
[2018-10-12 09:35:12 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 09:35:15 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 09:35:19 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 09:35:19 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 09:35:19 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 09:35:19 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 09:35:33 PM] - [MainThread] - [output_log.py-line:38] [WARNING] select * from message where uid like '%nima%' or name like '%nima%' or tel like '%nima%'or address like '%nima%';
[2018-10-12 09:36:55 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 09:36:58 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 09:37:02 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 09:37:02 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 09:37:02 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 09:37:02 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 09:37:05 PM] - [MainThread] - [output_log.py-line:38] [WARNING] select * from message where uid like '%nima%' or name like '%nima%' or tel like '%nima%'or address like '%nima%';
[2018-10-12 09:38:32 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 09:38:36 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 09:38:38 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 09:38:38 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 09:38:38 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 09:38:38 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 09:38:42 PM] - [MainThread] - [output_log.py-line:38] [WARNING] select * from message where uid like '%nima%' or name like '%nima%' or tel like '%nima%'or address like '%nima%';
[2018-10-12 09:39:01 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 成功导出csv 文件
[2018-10-12 09:40:22 PM] - [MainThread] - [output_log.py-line:38] [WARNING] select * from message where uid like '%nima%' or name like '%nima%' or tel like '%nima%'or address like '%nima%';
[2018-10-12 09:40:26 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 成功导出html 文件
[2018-10-12 09:43:49 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 09:43:53 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 09:43:55 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 09:43:55 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 09:43:55 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 09:43:55 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 09:43:57 PM] - [MainThread] - [output_log.py-line:38] [WARNING] select * from message where uid like '%nima%' or name like '%nima%' or tel like '%nima%'or address like '%nima%';
[2018-10-12 09:44:00 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 成功导出html 文件
[2018-10-12 09:56:26 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 09:56:28 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 09:56:29 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 401 83
[2018-10-12 09:56:29 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 09:56:29 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 09:56:29 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 09:56:31 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 09:56:32 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 401 83
[2018-10-12 09:56:32 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 09:56:32 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 09:56:32 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 09:56:33 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 09:56:34 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 401 83
[2018-10-12 09:56:34 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 09:56:34 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 09:56:34 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 09:56:34 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败，已锁定
[2018-10-12 09:56:36 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 09:56:36 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败，已锁定
[2018-10-12 10:01:52 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:01:57 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:02:00 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:02:00 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:02:00 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:02:00 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:02:07 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 9
[2018-10-12 10:02:07 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 更新数据，没有这个id用户信息
[2018-10-12 10:02:45 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 更新用户信息
[2018-10-12 10:02:45 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] update message set name='madan', age='24', tel='123432534543', address='hhaah', update_time='1539352962' where uid='8';
[2018-10-12 10:02:45 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] {'name': 'madan', 'age': '24', 'tel': '123432534543', 'address': 'hhaah'}
[2018-10-12 10:03:06 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 退出系统，关闭数据库连接
[2018-10-12 10:04:15 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:04:19 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:04:20 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:04:20 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:04:20 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:04:20 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:04:22 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 退出系统，关闭数据库连接
[2018-10-12 10:05:28 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:05:31 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:05:33 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:05:33 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:05:33 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:05:33 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:05:34 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 退出系统，关闭数据库连接
[2018-10-12 10:09:44 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:09:47 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:09:48 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:09:48 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:09:48 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:09:48 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:09:55 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 退出系统，关闭数据库连接
[2018-10-12 10:13:18 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:13:21 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:13:28 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:13:28 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:13:28 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:13:28 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:13:28 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 退出系统，关闭数据库连接
[2018-10-12 10:16:05 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:16:08 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:16:09 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:16:09 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:16:09 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:16:09 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:19:02 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:19:05 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:19:07 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:19:07 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:19:07 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:19:07 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:20:40 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:20:43 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:20:45 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:20:45 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:20:45 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:20:45 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:20:47 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 退出系统，关闭数据库连接
[2018-10-12 10:21:48 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:21:52 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:21:54 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:21:54 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:21:54 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:21:54 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:22:52 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:22:55 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:22:56 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:22:56 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:22:56 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:22:56 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:22:59 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 退出系统，关闭数据库连接
[2018-10-12 10:23:29 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:23:32 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:23:35 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:23:35 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:23:35 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:23:35 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:23:36 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 退出系统，关闭数据库连接
[2018-10-12 10:49:54 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:49:57 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:50:01 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:50:01 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:50:01 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:50:01 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:53:24 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:53:27 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:53:28 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:53:28 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:53:28 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:53:28 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:54:30 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:54:33 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:54:34 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:54:34 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:54:34 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:54:34 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:54:46 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:54:46 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败，已锁定
[2018-10-12 10:54:58 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:55:00 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:55:09 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:55:09 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:55:09 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:55:09 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:55:32 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:55:41 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:55:42 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:55:42 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:55:42 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:55:42 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:55:49 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 更新输入id非法
[2018-10-12 10:55:53 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 更新输入id非法
[2018-10-12 10:55:58 PM] - [MainThread] - [output_log.py-line:38] [WARNING] select * from message where uid like '%%' or name like '%%' or tel like '%%'or address like '%%';
[2018-10-12 10:56:08 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 退出系统，关闭数据库连接
[2018-10-12 10:56:10 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:56:13 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:56:15 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:56:15 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:56:15 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:56:15 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:56:16 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 退出系统，关闭数据库连接
[2018-10-12 10:57:07 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:57:08 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:57:10 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 401 83
[2018-10-12 10:57:10 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
[2018-10-12 10:57:10 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:57:10 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 用户信息错误，登陆失败
[2018-10-12 10:57:15 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:57:16 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:57:16 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:57:16 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:57:16 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:57:17 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 输入操作非法
[2018-10-12 10:58:28 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:58:32 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:58:33 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:58:33 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:58:33 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:58:33 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 10:58:40 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 10:58:42 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 10:58:43 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 10:58:43 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 10:58:43 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 10:58:43 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 11:02:31 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 11:02:34 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 11:02:37 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 11:02:37 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 11:02:37 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 11:02:37 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 11:04:58 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 11:05:00 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 11:05:02 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 11:05:02 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 11:05:02 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 11:05:02 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 11:05:20 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 11:05:22 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 11:05:24 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 11:05:24 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 11:05:24 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 11:05:24 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 11:05:25 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 输入操作非法
[2018-10-12 11:06:33 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 连接数据库了
[2018-10-12 11:06:36 PM] - [MainThread] - [connectionpool.py-line:823] [DEBUG] Starting new HTTPS connection (1): api.github.com:443
[2018-10-12 11:06:38 PM] - [MainThread] - [connectionpool.py-line:393] [DEBUG] https://api.github.com:443 "GET /user HTTP/1.1" 200 None
[2018-10-12 11:06:38 PM] - [MainThread] - [output_log.py-line:36] [INFO] {"login": "heyemmby", "id": 32669494, "node_id": "MDQ6VXNlcjMyNjY5NDk0", "avatar_url": "https://avatars0.githubusercontent.com/u/32669494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/heyemmby", "html_url": "https://github.com/heyemmby", "followers_url": "https://api.github.com/users/heyemmby/followers", "following_url": "https://api.github.com/users/heyemmby/following{/other_user}", "gists_url": "https://api.github.com/users/heyemmby/gists{/gist_id}", "starred_url": "https://api.github.com/users/heyemmby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/heyemmby/subscriptions", "organizations_url": "https://api.github.com/users/heyemmby/orgs", "repos_url": "https://api.github.com/users/heyemmby/repos", "events_url": "https://api.github.com/users/heyemmby/events{/privacy}", "received_events_url": "https://api.github.com/users/heyemmby/received_events", "type": "User", "site_admin": false, "name": "emmby", "company": null, "blog": "", "location": null, "email": null, "hireable": null, "bio": "\u4eba\u4f1a\u98de\u4e48\u3001\uff1f\u5982\u679c\u5168\u4e16\u754c\u7684\u4eba\u90fd\u544a\u8bc9\u6211 \u4e0d\u80fd\u3001\u6211\u662f\u8be5\u653e\u5f03\uff0c\u8fd8\u662f \u9119\u89c6\u4ed6\u4eec\uff0c\uff0c\uff0c", "public_repos": 1, "public_gists": 0, "followers": 0, "following": 0, "created_at": "2017-10-10T09:20:48Z", "updated_at": "2018-09-15T16:09:53Z"}
[2018-10-12 11:06:38 PM] - [MainThread] - [output_log.py-line:36] [INFO] https://api.github.com/user
[2018-10-12 11:06:38 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 登陆成功
[2018-10-12 11:06:39 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 输入操作非法
[2018-10-12 11:06:42 PM] - [MainThread] - [output_log.py-line:38] [WARNING] 输入操作非法
[2018-10-12 11:06:45 PM] - [MainThread] - [output_log.py-line:34] [DEBUG] 退出系统，关闭数据库连接
